project_id = "hdylxvyvateaephkbccy"

[functions.generate-lesson-plan]
verify_jwt = false

[functions.refine-email]
verify_jwt = false

[functions.generate-lesson-outputs]
verify_jwt = false

[functions.convert-to-asset]
verify_jwt = false

[functions.generate-distractors]
verify_jwt = false

[functions.extract-ocr]
verify_jwt = false

[functions.refine-topics]
verify_jwt = false