import { useEffect, useState } from "react";
import { ChevronDown, Info } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

const NAVY = "#14213D";
const RED = "#CE1126";
const GREEN = "#16A34A";

interface Course {
  id: string;
  name: string;
  subtext?: string;
  availability: string;
  cta: string;
  status: "live" | "upcoming" | "future";
  slug: string;
}

interface StagingCoursesSectionProps {
  courses: Course[];
  onCardClick: (course: Course) => void;
  onChapterClick?: (course: Course, chapterNumber: number) => void;
  onExpansionClick?: () => void;
}

const DISPLAY_ORDER = [
  "intro-accounting-1",
  "intro-accounting-2",
  "intermediate-accounting-1",
  "intermediate-accounting-2",
];

const SUBTEXT_BY_SLUG: Record<string, string> = {
  "intro-accounting-1": "Financial Principles",
  "intro-accounting-2": "Managerial Principles",
};

const TEXTBOOK_BY_SLUG: Record<string, string> = {
  "intro-accounting-1": "Based on Principles of Accounting (McGraw Hill)",
  "intro-accounting-2": "Based on Principles of Accounting (McGraw Hill)",
  "intermediate-accounting-1": "Based on Intermediate Accounting, 18th Ed. (Wiley)",
  "intermediate-accounting-2": "Based on Intermediate Accounting, 18th Ed. (Wiley)",
};

const BULLETS: { text: string; tooltip: string }[] = [
  {
    text: "Cram tools for every chapter",
    tooltip:
      "Flashcards, journal entries, and formula sheets — generated by AI and reviewed by Lee so you're studying the right things, not just anything.",
  },
  {
    text: "2,500 practice problems with AI explanations",
    tooltip:
      "Every solution is AI-generated using Lee's 10+ years of tutoring patterns, then spot-checked for accuracy. Think of it as a solutions manual built by your tutor, not a textbook publisher.",
  },
  {
    text: "Ask Lee — get a personalized video back",
    tooltip:
      "Stuck on something? Submit your question directly from any problem page. Lee reviews it and records a video response, personally.",
  },
];

interface Chapter {
  id: string;
  chapter_number: number;
  chapter_name: string;
  course_id: string;
}

export default function StagingCoursesSection({
  courses,
  onCardClick,
  onChapterClick,
}: StagingCoursesSectionProps) {
  const ordered = DISPLAY_ORDER
    .map((slug) => courses.find((c) => c.slug === slug))
    .filter(Boolean) as Course[];

  // No pre-selection
  const [selectedSlug, setSelectedSlug] = useState<string>("");
  const [open, setOpen] = useState(false);
  const [chapters, setChapters] = useState<Chapter[]>([]);

  const selected = ordered.find((c) => c.slug === selectedSlug);

  useEffect(() => {
    if (!selected) {
      setChapters([]);
      return;
    }
    let cancelled = false;
    (async () => {
      const { data } = await supabase
        .from("chapters")
        .select("id, chapter_number, chapter_name, course_id")
        .eq("course_id", selected.id)
        .order("chapter_number", { ascending: true });
      if (!cancelled) setChapters((data ?? []) as Chapter[]);
    })();
    return () => {
      cancelled = true;
    };
  }, [selected?.id]);

  return (
    <section className="px-4 sm:px-6 py-12 sm:py-16" style={{ background: "#F8F8FA" }}>
      <style>{`
        @keyframes betaPulse {
          0%, 100% { transform: scale(1); opacity: 1; }
          50% { transform: scale(1.4); opacity: 0.6; }
        }
      `}</style>

      <div className="mx-auto max-w-[720px]">
        {/* Integrated beta banner */}
        <TooltipProvider delayDuration={150}>
          <div className="flex flex-col sm:flex-row sm:items-center gap-3 sm:gap-4 mb-5">
            <span
              className="inline-flex items-center gap-2 self-start px-3 py-1.5 rounded-full text-[12px] font-bold whitespace-nowrap"
              style={{
                background: "rgba(22,163,74,0.12)",
                color: GREEN,
                fontFamily: "Inter, sans-serif",
              }}
            >
              <span className="relative inline-block w-2 h-2">
                <span className="absolute inset-0 rounded-full" style={{ background: GREEN }} />
                <span
                  className="absolute inset-0 rounded-full"
                  style={{ background: GREEN, animation: "betaPulse 1.8s ease-in-out infinite" }}
                />
              </span>
              Spring 2026 is Live
            </span>
          </div>

          <ul className="space-y-2.5 mb-8">
            {BULLETS.map((b, i) => (
              <li
                key={i}
                className="flex items-start gap-3 text-[14px] sm:text-[15px] leading-relaxed"
                style={{ color: NAVY, fontFamily: "Inter, sans-serif" }}
              >
                <span
                  className="flex-shrink-0 mt-[7px] w-1.5 h-1.5 rounded-full"
                  style={{ background: GREEN }}
                />
                <span className="flex items-center gap-1.5">
                  <span>{b.text}</span>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <button
                        type="button"
                        className="inline-flex items-center justify-center cursor-help"
                        aria-label="More info"
                      >
                        <Info className="w-3.5 h-3.5" style={{ color: "#9CA3AF" }} />
                      </button>
                    </TooltipTrigger>
                    <TooltipContent side="top" className="max-w-[280px] text-xs leading-relaxed">
                      {b.tooltip}
                    </TooltipContent>
                  </Tooltip>
                </span>
              </li>
            ))}
          </ul>
        </TooltipProvider>

        <p
          className="text-center text-[13px] sm:text-[14px] font-semibold uppercase tracking-[0.15em] mb-4"
          style={{ color: "#6B7280", fontFamily: "Inter, sans-serif" }}
        >
          Which course are you studying?
        </p>

        {/* Dropdown */}
        <div className="relative">
          <button
            onClick={() => setOpen((v) => !v)}
            className="w-full rounded-2xl px-5 py-4 flex items-center justify-between text-left transition-all hover:shadow-md"
            style={{
              background: "#fff",
              borderLeft: `4px solid ${NAVY}`,
              boxShadow: "0 8px 32px rgba(0,0,0,0.08), 0 0 0 1px rgba(0,0,0,0.04)",
              fontFamily: "Inter, sans-serif",
            }}
          >
            <div className="flex flex-col">
              {selected ? (
                <>
                  <span className="text-[18px] sm:text-[20px] font-bold leading-tight" style={{ color: NAVY }}>
                    {selected.name}
                  </span>
                  {SUBTEXT_BY_SLUG[selected.slug] && (
                    <span className="text-[13px] mt-0.5" style={{ color: "#6B7280" }}>
                      {SUBTEXT_BY_SLUG[selected.slug]}
                    </span>
                  )}
                </>
              ) : (
                <span className="text-[17px] sm:text-[19px] font-semibold leading-tight" style={{ color: "#9CA3AF" }}>
                  Select your course →
                </span>
              )}
            </div>
            <ChevronDown
              className="w-5 h-5 flex-shrink-0 transition-transform"
              style={{ color: NAVY, transform: open ? "rotate(180deg)" : "none" }}
            />
          </button>

          {open && (
            <div
              className="absolute z-20 left-0 right-0 mt-2 rounded-2xl overflow-hidden"
              style={{
                background: "#fff",
                boxShadow: "0 12px 40px rgba(0,0,0,0.15), 0 0 0 1px rgba(0,0,0,0.06)",
              }}
            >
              {ordered.map((c) => (
                <button
                  key={c.slug}
                  onClick={() => {
                    setSelectedSlug(c.slug);
                    setOpen(false);
                  }}
                  className="w-full px-5 py-3 text-left transition-colors hover:bg-slate-50"
                  style={{ fontFamily: "Inter, sans-serif" }}
                >
                  <div className="text-[15px] font-semibold" style={{ color: NAVY }}>
                    {c.name}
                  </div>
                  {SUBTEXT_BY_SLUG[c.slug] && (
                    <div className="text-[12px]" style={{ color: "#6B7280" }}>
                      {SUBTEXT_BY_SLUG[c.slug]}
                    </div>
                  )}
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Textbook + Chapters — only after selection */}
        {selected && (
          <div
            className="mt-5 rounded-2xl p-5 sm:p-6"
            style={{
              background: "#fff",
              boxShadow: "0 4px 20px rgba(0,0,0,0.06), 0 0 0 1px rgba(0,0,0,0.04)",
              fontFamily: "Inter, sans-serif",
            }}
          >
            {/* Stat cards */}
            <div className="grid grid-cols-3 gap-2 sm:gap-3 mb-5">
              {[
                { title: "250+ Practice Problems", subtext: "Step-by-step AI solutions" },
                { title: "Cram Tools", subtext: "Every chapter covered" },
                { title: "Ask Lee", subtext: "Personalized video responses" },
              ].map((stat) => (
                <div
                  key={stat.title}
                  className="rounded-xl p-3 sm:p-4 text-center"
                  style={{ background: "#F8F8FA" }}
                >
                  <div
                    className="text-[12px] sm:text-[13px] font-bold leading-tight"
                    style={{ color: NAVY }}
                  >
                    {stat.title}
                  </div>
                  <div
                    className="text-[10px] sm:text-[11px] mt-1 leading-snug"
                    style={{ color: "#6B7280" }}
                  >
                    {stat.subtext}
                  </div>
                </div>
              ))}
            </div>

            {chapters.length === 0 ? (
              <p className="text-[13px]" style={{ color: "#9CA3AF" }}>
                Loading chapters…
              </p>
            ) : (
              <ul className="flex flex-col mb-5 -mx-2">
                {chapters.map((ch) => (
                  <li key={ch.id}>
                    <button
                      type="button"
                      onClick={() =>
                        onChapterClick
                          ? onChapterClick(selected, ch.chapter_number)
                          : onCardClick(selected)
                      }
                      className="w-full flex items-baseline gap-2 text-[14px] text-left rounded-lg px-2 py-2 transition-colors hover:bg-slate-50 cursor-pointer"
                      style={{ color: NAVY }}
                    >
                      <span className="text-[12px] font-semibold w-12 flex-shrink-0" style={{ color: "#9CA3AF" }}>
                        Ch. {ch.chapter_number}
                      </span>
                      <span>{ch.chapter_name}</span>
                    </button>
                  </li>
                ))}
              </ul>
            )}

            <button
              onClick={() => onCardClick(selected)}
              className="w-full rounded-xl px-5 py-3 text-[14px] font-bold text-white transition-all hover:brightness-110 active:scale-[0.99]"
              style={{ background: RED, fontFamily: "Inter, sans-serif" }}
            >
              Preview Free →
            </button>
          </div>
        )}

        <p
          className="mt-8 text-center text-[14px]"
          style={{ color: "#4A5568", fontFamily: "Inter, sans-serif" }}
        >
          Started at University of Mississippi. Built for accounting students anywhere.
        </p>
      </div>
    </section>
  );
}
