import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from "@/components/ui/dialog";
import { RefreshCw, Lock, Unlock } from "lucide-react";
import { toast } from "sonner";
import { logActivity } from "@/lib/activityLogger";
import { runValidation, hasFailures, type AnswerPackageData } from "@/lib/validation";

interface Props {
  sourceProblemId: string;
  latestPackage?: any;
  openRepairNotes?: any[];
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function RegenerateDialog({ sourceProblemId, latestPackage, openRepairNotes, open, onOpenChange }: Props) {
  const qc = useQueryClient();
  const [lockProblemText, setLockProblemText] = useState(true);
  const [lockQuestionFormatting, setLockQuestionFormatting] = useState(true);
  const [lockAnswerChoices, setLockAnswerChoices] = useState(false);
  const [lockExplanations, setLockExplanations] = useState(false);

  const regenMutation = useMutation({
    mutationFn: async () => {
      const { data: { user } } = await supabase.auth.getUser();
      
      const repairNoteIds = openRepairNotes?.map((n) => n.id) ?? [];
      const lockFlags = {
        lock_problem_text: lockProblemText,
        lock_question_formatting: lockQuestionFormatting,
        lock_answer_choices: lockAnswerChoices,
        lock_explanations: lockExplanations,
      };

      // 1. Create generation job
      const { data: job, error: jobErr } = await supabase.from("generation_jobs").insert({
        source_problem_id: sourceProblemId,
        requested_by: user?.id ?? null,
        job_type: repairNoteIds.length > 0 ? "regenerate_with_repair_note" as any : "generate" as any,
        input_payload: {
          repair_note_ids: repairNoteIds,
          lock_flags: lockFlags,
          previous_package_id: latestPackage?.id ?? null,
        },
        status: "queued" as any,
      } as any).select("id").single();
      if (jobErr) throw jobErr;

      await logActivity({
        actor_type: "user",
        entity_type: "source_problem",
        entity_id: sourceProblemId,
        event_type: "REGEN_JOB_CREATED",
        payload_json: { job_id: job.id, lock_flags: lockFlags, repair_note_ids: repairNoteIds },
      });

      // 2. Mark job running
      await supabase.from("generation_jobs").update({ status: "running" as any } as any).eq("id", job.id);
      await logActivity({
        actor_type: "system",
        entity_type: "source_problem",
        entity_id: sourceProblemId,
        event_type: "REGEN_STARTED",
        payload_json: { job_id: job.id },
      });

      // 3. Build new answer package (merge locked fields from previous)
      const nextVersion = (latestPackage?.version ?? 0) + 1;
      const prevPayload = latestPackage?.answer_payload ?? {};
      const prevInputs = latestPackage?.extracted_inputs ?? {};

      // For now, create a new package preserving locked content
      const newPayload = { ...prevPayload };
      if (!lockAnswerChoices) {
        // Would be regenerated by AI — placeholder for now
        newPayload._regenerated_answers = true;
      }
      if (!lockExplanations) {
        newPayload._regenerated_explanations = true;
      }

      const pkgData: AnswerPackageData = {
        answer_payload: newPayload,
        extracted_inputs: prevInputs,
        computed_values: latestPackage?.computed_values ?? {},
      };
      const validationResults = runValidation(pkgData);
      const status = hasFailures(validationResults) ? "needs_review" : "drafted";

      const { data: newPkg, error: pkgErr } = await supabase.from("answer_packages").insert({
        source_problem_id: sourceProblemId,
        version: nextVersion,
        generator: repairNoteIds.length > 0 ? "mixed" as any : "system" as any,
        extracted_inputs: prevInputs,
        computed_values: latestPackage?.computed_values ?? {},
        answer_payload: newPayload,
        validation_results: validationResults as any,
        status: status as any,
      } as any).select("id").single();
      if (pkgErr) throw pkgErr;

      await logActivity({
        actor_type: "system",
        entity_type: "source_problem",
        entity_id: sourceProblemId,
        event_type: "ANSWER_PACKAGE_CREATED",
        payload_json: { package_id: newPkg.id, version: nextVersion, status, validation_results: validationResults },
      });

      // 4. Mark repair notes resolved
      if (repairNoteIds.length > 0) {
        await supabase.from("repair_notes").update({
          status: "resolved" as any,
          resolved_at: new Date().toISOString(),
        } as any).in("id", repairNoteIds);
      }

      // 5. Mark job done
      await supabase.from("generation_jobs").update({
        status: "done" as any,
        completed_at: new Date().toISOString(),
      } as any).eq("id", job.id);

      await logActivity({
        actor_type: "system",
        entity_type: "source_problem",
        entity_id: sourceProblemId,
        event_type: "REGEN_FINISHED",
        payload_json: { job_id: job.id, package_id: newPkg.id },
      });
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["answer-packages"] });
      qc.invalidateQueries({ queryKey: ["repair-notes"] });
      qc.invalidateQueries({ queryKey: ["activity-log"] });
      onOpenChange(false);
      toast.success("Regeneration complete — new answer package created");
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const LockToggle = ({ label, locked, onChange }: { label: string; locked: boolean; onChange: (v: boolean) => void }) => (
    <div className="flex items-center justify-between py-1.5">
      <div className="flex items-center gap-2">
        {locked ? <Lock className="h-3 w-3 text-muted-foreground" /> : <Unlock className="h-3 w-3 text-primary" />}
        <Label className="text-xs">{label}</Label>
      </div>
      <Switch checked={locked} onCheckedChange={onChange} />
    </div>
  );

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <RefreshCw className="h-4 w-4" /> Regenerate (This Problem Only)
          </DialogTitle>
          <DialogDescription>
            Creates a new answer package version. Locked fields are preserved from v{latestPackage?.version ?? "?"}.
            {openRepairNotes && openRepairNotes.length > 0 && (
              <span className="block mt-1 text-amber-400">{openRepairNotes.length} open repair note(s) will guide regeneration and auto-resolve.</span>
            )}
          </DialogDescription>
        </DialogHeader>

        <div className="border border-border rounded-lg p-3 space-y-0.5">
          <p className="text-[10px] font-semibold text-muted-foreground uppercase mb-1">Lock Options</p>
          <LockToggle label="Problem Text" locked={lockProblemText} onChange={setLockProblemText} />
          <LockToggle label="Question Formatting" locked={lockQuestionFormatting} onChange={setLockQuestionFormatting} />
          <LockToggle label="Answer Choices" locked={lockAnswerChoices} onChange={setLockAnswerChoices} />
          <LockToggle label="Explanations" locked={lockExplanations} onChange={setLockExplanations} />
        </div>

        <DialogFooter>
          <Button variant="outline" size="sm" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button size="sm" onClick={() => regenMutation.mutate()} disabled={regenMutation.isPending}>
            {regenMutation.isPending ? "Regenerating…" : "Regenerate"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
